
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

patch_num: 1
patch_factor: 1
stride_factor: 1

style_dim: 16

save_iter: 1000
log_iter: 500
model_module: runners.modelAEadj_flexdp2_unsup_triplet
cycle_factor: 10
recon_loss: MSE
cycle_loss: L1
lr: 0.0001
se_lr: 0.0001
nt_xent_factor: 1.
tau: 0.5
style_batch: 4
kernel: 5
dilation: True
pooling: max

buildings_dir:
data_filename: model_filled.binvox
style_filename: model_depth_fusion.binvox
datapath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/export_furniture.txt
stylepath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/style_chair_64.txt
data_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_furniture
style_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2
style_indices: "6, 17, 21, 22, 25, 27, 3, 15, 20"
#style_indices: "6, 1, 9, 3, 4, 12, 15"
#style_indices: "2, 3, 7, 8, 11, 14, 15, 16"
#style_indices: "0, 3, 4, 8, 11, 15, 17, 24, 26, 27, 29, 31"
style_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/03001627
data_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/furniture

checkpoint_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep1/trained_on_chairs/unsup_triplet/ajd_flexdp2_unsup_triplet/checkpoints
sample_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep1/trained_on_chairs/unsup_triplet/ajd_flexdp2_unsup_triplet/samples_again
export_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep1/trained_on_chairs/unsup_triplet/ajd_flexdp2_unsup_triplet/encodings
test_fig_3_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep1/trained_on_chairs/unsup_triplet/ajd_flexdp2_unsup_triplet/test_fig_3
style_codes_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep1/trained_on_chairs/unsup_triplet/ajd_flexdp2_unsup_triplet/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: False
export: True
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
