
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

patch_num: 1
patch_factor: 1
stride_factor: 1

gen_dim: 32
disc_dim: 32

save_iter: 1000
log_iter: 500
model_module: runners_pytorch3d.modelAEadain_dp2
cycle_factor: 10
recon_loss: MSE
cycle_loss: L1
lr: 0.0001
se_lr: 0.0001
nt_xent_factor: 1.
tau: 0.5
style_batch: 4
kernel: 5
dilation: True
pooling: max

triplet_splits: /home/czavou01/furniture-triplet-splits
buildings_dir:
data_filename: model_filled.binvox
style_filename: model_filled.binvox
datapath: /home/czavou01/decorgan-logs/splits/export_furniture.txt
stylepath: /home/czavou01/decorgan-logs/splits/furniture_styles32.txt
data_cache_dir: /home/czavou01/decorgan-logs/data_cached_2
style_cache_dir: /home/czavou01/decorgan-logs/data_cached_2
style_dir: /home/czavou01/decorgan-logs/preprocessed_data/furniture
data_dir: /home/czavou01/decorgan-logs/preprocessed_data/furniture

checkpoint_dir: /home/czavou01/decorgan-models/furniture/adain_dp2_in16_out128/checkpoints
sample_dir: /home/czavou01/decorgan-models/furniture/adain_dp2_in16_out128/samples/
export_dir: /home/czavou01/decorgan-models/furniture/adain_dp2_in16_out128/encodings/
test_fig_3_dir: /home/czavou01/decorgan-models/furniture/adain_dp2_in16_out128/test_fig_3
style_codes_dir: /home/czavou01/decorgan-models/furniture/adain_dp2_in16_out128/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: False
export: False
debug: False
finetune: True
pct_suffix: _3%

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
