
#our_cypriot_encodings_dir ?= /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_buildings/setA/original_clean/s8/encodings_religious_and_cypriot/discr_all/max
#our_cypriot_model ?= decorgan_original
#our_cypriot_model_yml ?= original_s8
#our_cypriot_encodings_dir ?= /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_buildings/setA/ajd_flexdp2/in16_out128/encodings_religious_cypriot/discr_all/max
#our_cypriot_model ?= decorgan_with_se
#our_cypriot_model_yml ?= adj_s32
our_cypriot_encodings_dir ?= /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_buildings/setA/adain_dp2_in16_out128/g32d32/encodings_religious_and_cypriot
our_cypriot_model ?= decorgan_adain_p2_in16_out128_g32d32
our_cypriot_model_yml ?= adain_p2_in16_out128_g32d32
our_cypriot_objs:
	cd $(style_detection_src)/common && python move_files.py --in_dir /media/graphicslab/BigData1/zavou/ANNFASS_DATA/ANNFASS_Buildings_may/normalizedObj --out_dir $(other_objs_dir)/our_cypriot --ext ".obj" --rename "" --copy True
our_cypriot_decorgan_preprocess:
	cd $(decor_gan_private_src)/data_preprocess && python preprocess_some_components.py our_cypriot $(other_objs_dir)$(decorgan_logs)/preprocessed_data "" False 0 1 ""
# put them with buildnet_buildings ...
our_building_cross_val:
	cd $(style_detection_src)/splits/religious_and_cypriot && python create_cross_val.py --buildings_csv /media/graphicslab/BigData1/zavou/ANNFASS_DATA/Combined_Buildings/buildings_with_style.csv --out_dir $(styledetect_logs)/our_data/building --num_folds 5 --styles 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque' --expected_total 53
our_building_export_txt:
	cd $(style_detection_src)/splits && python create_building_or_component_txt_files_decorgan.py --data_dirs $(decorgan_logs)/preprocessed_data/buildnet_buildings/normalizedObj --elements "window,door,column,dome,tower" --buildings_csv /media/graphicslab/BigData1/zavou/ANNFASS_DATA/Combined_Buildings/buildings_with_style.csv --txt_file /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/buildnet_buildings/buildnet_annfass_buildings.txt --per_element False
our_building_export:
	cd $(decor_gan_private_src) && $(decor_py) mymain.py --config_yml settings/local/export/trained_on_buildnet_buildings/religious_and_annfass/$(our_cypriot_model_yml).yml --gpu 0
#our_building_csv:
#	cd $(style_detection_src)/sklearn_impl/religious_and_cypriot && python split_csv_generation.py --buildings_csv /media/graphicslab/BigData1/zavou/ANNFASS_DATA/Combined_Buildings/buildings_with_style.csv --data_dirs $(our_cypriot_encodings_dir) --out_dir $(styledetect_logs)/our_data/building/$(our_cypriot_model)/classification_cross_val_$(cross_val)_csv --splits $(styledetect_logs)/our_data/building/classification_cross_val_$(cross_val).json --styles 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque' --expected_total 53
our_building_csv_wrapper:
	cd $(style_detection_src)/sklearn_impl/religious_and_cypriot && python split_csv_generation_wrapper.py --buildings_csv /media/graphicslab/BigData1/zavou/ANNFASS_DATA/Combined_Buildings/buildings_with_style.csv --data_dir $(our_cypriot_encodings_dir) --out_dir $(styledetect_logs)/our_data/building/$(our_cypriot_model)/classification_cross_val_$(cross_val)_csv --splits $(styledetect_logs)/our_data/building/classification_cross_val_$(cross_val).json --styles 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque' --expected_total 53 --py_exe $(style_detect_py)
#our_building_svm:
	#cd $(style_detection_src)/sklearn_impl/ && python run_svm.py --data_dir $(styledetect_logs)/our_data/building/$(our_cypriot_model)/classification_cross_val_$(cross_val)_csv --models_dir $(styledetect_logs)/our_data/building/$(our_cypriot_model)/classification_cross_val_$(cross_val)_svm --folds $(cross_val) --svm_impl simple --classes 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque'
our_building_svm_wrapper:
	cd $(style_detection_src)/sklearn_impl/ && python run_svm_wrapper_other.py --data_dir $(styledetect_logs)/our_data/building/$(our_cypriot_model)/classification_cross_val_$(cross_val)_csv --models_dir $(styledetect_logs)/our_data/building/$(our_cypriot_model)/classification_cross_val_$(cross_val)_svm --folds $(cross_val) --svm_impl simple --classes 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque' --py_exe $(style_detect_py)



our_column_encodings_dir ?= /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_components/setA/original_clean/s8/encodings_windowdoorcolumndometower/discr_all/max
our_column_model ?= decorgan_original
our_column_model_yml ?= original_s8
our_columndometower_cross_val:
	cd $(style_detection_src)/splits/religious_and_cypriot && python create_cross_val_independent_component.py --buildings_csv /media/graphicslab/BigData1/zavou/ANNFASS_DATA/Combined_Buildings/buildings_with_style.csv --in_dir /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components --out_dir $(styledetect_logs)/our_data/columndometower --num_folds $(cross_val) --styles 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque' --expected_buildings 49 --elements 'dome,tower,column'
our_component_export_txt:
	cd $(style_detection_src)/splits && python create_building_or_component_txt_files_decorgan.py --data_dirs $(decorgan_logs)/preprocessed_data/groups_june17_uni_nor_components --elements "window,door,column,dome,tower" --buildings_csv /media/graphicslab/BigData1/zavou/ANNFASS_DATA/Combined_Buildings/buildings_with_style.csv --txt_file /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/building_component/building_component.txt --per_element True
our_component_export:
	cd $(decor_gan_private_src) && $(decor_py) mymain.py --config_yml settings/local/export/trained_on_buildnet_component/religious_and_annfass/$(our_column_model_yml).yml --gpu 0
our_columndometower_csv:
	cd $(style_detection_src)/sklearn_impl/religious_and_cypriot && python split_csv_generation_component.py --buildings_csv /media/graphicslab/BigData1/zavou/ANNFASS_DATA/Combined_Buildings/buildings_with_style.csv --data_dirs $(our_column_encodings_dir) --out_dir $(styledetect_logs)/our_data/columndometower/$(our_column_model)/classification_cross_val_$(cross_val)_csv --splits $(styledetect_logs)/our_data/columndometower/classification_cross_val_$(cross_val).json --styles 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque' --expected_total 107
our_columndometower_svm:
	cd $(style_detection_src)/sklearn_impl/ && python run_svm.py --data_dir $(styledetect_logs)/our_data/columndometower/$(our_column_model)/classification_cross_val_$(cross_val)_csv --models_dir $(styledetect_logs)/our_data/columndometower/$(our_column_model)/classification_cross_val_$(cross_val)_svm --folds $(cross_val) --svm_impl simple --classes 'neo_classicism,ottoman,gothic,byzantine,baroque,romanesque'

