
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

patch_num: 1
patch_factor: 1
stride_factor: 1

save_iter: 1000
log_iter: 500
model_module: runners.modelAE_flexdp2
cycle_factor: 10
recon_loss: MSE
cycle_loss: L1
lr: 0.0001
se_lr: 0.0001
style_dim: 8
nt_xent_factor: 1.
tau: 0.5
style_batch: 4
kernel: 5
dilation: True
pooling: max

buildings_dir:
data_filename: model_filled.binvox
style_filename: model_filled.binvox
datapath: /home/czavou01/decorgan-logs/splits/export_furniture.txt
stylepath: /home/czavou01/decorgan-logs/splits/furniture_styles32.txt
data_cache_dir: /home/czavou01/decorgan-logs/data_cached_2
style_cache_dir: /home/czavou01/decorgan-logs/data_cached_2
style_dir: /home/czavou01/decorgan-logs/preprocessed_data/furniture
data_dir: /home/czavou01/decorgan-logs/preprocessed_data/furniture

checkpoint_dir: /home/czavou01/decorgan-models/furniture/original_s8/checkpoints
sample_dir: /home/czavou01/decorgan-models/furniture/original_s8/samples/
export_dir: /home/czavou01/decorgan-models/furniture/original_s8/encodings/
test_fig_3_dir: /home/czavou01/decorgan-models/furniture/original_s8/test_fig_3
style_codes_dir: /home/czavou01/decorgan-models/furniture/original_s8/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: False
export: False
debug: False

output_for_eval_dir: /home/czavou01/decorgan-models/furniture/original_s8/output_for_eval
output_for_FID_dir: /home/czavou01/decorgan-models/furniture/original_s8/output_for_FID
unique_patches_dir: /home/czavou01/decorgan-models/furniture/original_s8/unique_patches_64_chairs
eval_output_dir: /home/czavou01/decorgan-models/furniture/original_s8/eval_output
cls_dir: /home/czavou01/decorgan-logs/Clsshapenet_weights

prepvox: True
prepvoxstyle: True
evalvox: True

prepimg: False
prepimgreal: False
evalimg: False

prepFID: True
prepFIDmodel: True
prepFIDreal: True
evalFID: True
ui: False
