
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

gen_dim: 32
disc_dim: 32
style_dim: 16

save_iter: 3141
log_iter: 785
model_module: runners.modelAE_flexdp2
recon_loss: MSE
lr: 0.0001
kernel: 5
dilation: True
pooling: max

data_filename: model_filled.binvox
style_filename: model_depth_fusion.binvox
datapath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/HU_YU_LUN_BUILDNET/splits/car_hu_norm_and_align/export.txt
stylepath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/car/style_car_32.txt
data_cache_dir:
style_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2_in32_out256
data_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/HU_YU_LUN_BUILDNET/preprocessed_data/car_hu_norm_and_align
style_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/02958343

checkpoint_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_cars/original/i32o256N32/z16_a02/checkpoints
sample_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_cars/original/i32o256N32/z16_a02/samples
export_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_cars/original/i32o256N32/z16_a02/encodings_car_hu_norm_and_align
test_fig_3_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_cars/original/i32o256N32/z16_a02/test_fig_3
style_codes_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_cars/original/i32o256N32/z16_a02/style_codes

input_size: 32
output_size: 256

asymmetry: True

alpha: 0.2
beta: 10.0

train: False
style_codes: False
test_fig_3: False
export: True
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
