
epoch: 50
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 128

batch_size: 1
save_iter: 1000
log_iter: 500
model_module: runners.any_style.modelAEany_share_x_batchdiv
recon_loss: MSE
lr: 0.0001
margin: 0.2
kernel: 5
dilation: True
pooling: max

num_pairs: 64
num_triplets: 128

data_filename: model_filled.binvox
style_filename: model_depth_fusion.binvox
val_filename: model_depth_fusion.binvox
datapath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/HU_YU_LUN_BUILDNET/splits/chair_yu_norm_and_align/export.txt
stylepath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/chair/style_chair_64.txt
valpath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/chair/content_chair_test.txt
data_cache_dir:
style_cache_dir:
val_cache_dir:
data_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/HU_YU_LUN_BUILDNET/preprocessed_data/chair_yu_norm_and_align
style_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/data/03001627
val_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/data/03001627
style_indices: "6, 17, 21, 22, 25, 27, 3, 15, 20"

checkpoint_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/g32d32z128/batch1/triplets128pairs64margin0.2.sumlossdrealfake.good/checkpoints
sample_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/g32d32z128/batch1/triplets128pairs64margin0.2.sumlossdrealfake.good/samples
export_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/g32d32z128/batch1/triplets128pairs64margin0.2.sumlossdrealfake.good/encodings_chair_yu_norm_and_align
test_fig_3_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/g32d32z128/batch1/triplets128pairs64margin0.2.sumlossdrealfake.good/test_fig_3
style_codes_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/g32d32z128/batch1/triplets128pairs64margin0.2.sumlossdrealfake.good/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 1.
beta: 10.0
gamma: 1.
delta: 1.

train: False
style_codes: False
test_fig_3: False
export: True
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
