# Parameters for: training on buildnet buildings

SOLVER:
  gpu: 0,
  logdir: /home/graphicslab/Desktop/annfass_playground/inference_production/encodings_from_ocnn/
  max_iter: 144000 #60 epochs
  test_iter: 1
  test_every_iter: 2400
  run: infer  # infer / train / test / timeline
  lr_type: 'cos'
  learning_rate: 0.1
  step_size: 70,
  gamma: 0.1
  verbose: True

DATA:
  train:
    dtype: points
    depth: 6
    axis: y
    node_dis: False
    shuffle: True
    take: -1
    adaptive: False
    normalise: False
    batch_size: 8
    mask_ratio: 0.7
    return_pts: True
#    sigma: 0.0
    use_majority: True
    hsv: False
    rot_num: 12
    no_alpha: True
    zero_mean: False

  test:
    dtype: points
    depth: 6
    axis: y
    node_dis: False
    adaptive: False
    label_location: ""
    mask_ratio: 0.0
    sigma: 0.0
    rot_num: 1
    shuffle: True
    batch_size: 1
    return_pts: True
    use_majority: True
    hsv: False
    normalise: False
    no_alpha: True
    zero_mean: False


MODEL:
  name: hrnet
  channel: 3
  nout: 31
  depth: 6
  factor: 2
  signal_abs: True
  stages: 3

LOSS:
  num_class: 31
  momentum: 0.9
  weight_decay: 0.0005
  point_wise: True
  class_weights: ./configs/loss_weights/inv_log_weights.txt