
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

save_iter: 1000
log_iter: 500
model_module: runners.modelAEadj_flexdp2
recon_loss: MSE
lr: 0.0001
kernel: 5
dilation: True
pooling: max

data_filename: model_filled.binvox
style_filename: model_filled.binvox
datapath: /home/czavou01/decorgan-logs/splits/building_component/building_windowdoorcolumndometower_setAbalanced.txt
stylepath: /home/czavou01/decorgan-logs/splits/building_component/building_windowdoorcolumndometower_setAstyles32.txt
data_cache_dir: /home/czavou01/decorgan-logs/data_cached_2
style_cache_dir: /home/czavou01/decorgan-logs/data_cached_2
style_dir: /home/czavou01/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components
data_dir: /home/czavou01/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components

checkpoint_dir: /home/czavou01/decorgan-models/buildnet_component/setA/adj_dp2/s32/checkpoints
sample_dir: /home/czavou01/decorgan-models/buildnet_component/setA/adj_dp2/s32/samples
export_dir: /home/czavou01/decorgan-models/buildnet_component/setA/adj_dp2/s32/encodings
test_fig_3_dir: /home/czavou01/decorgan-models/buildnet_component/setA/adj_dp2/s32/test_fig_3
style_codes_dir: /home/czavou01/decorgan-models/buildnet_component/setA/adj_dp2/s32/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
