
epoch: 20
iteration: 0

g_steps: 2
d_steps: 2
r_steps: 5

patch_num: 8
patch_factor: 2
stride_factor: 2

save_iter: 1000
log_iter: 500
model_module: runners_pytorch3d.mymodelAE_dp2_patch2D
cycle_factor: 10
recon_loss: MSE
cycle_loss: L1
lr: 0.0001
se_lr: 0.0001
style_dim: 8
nt_xent_factor: 1.
tau: 0.5
style_batch: 4
kernel: 5
dilation: True
pooling: max

buildings_dir:
filename: model_depth_fusion.binvox
datapath: /home/czavou01/decorgan-logs/splits/content_chair_train.txt
cache_dir: /home/czavou01/decorgan-logs/data_cached_2
stylepath: /home/czavou01/decorgan-logs/splits/style_chair_64.txt
data_dir: /home/czavou01/decorgan-logs/data/03001627
checkpoint_dir: /home/czavou01/decorgan-models/mydp2patch2D_32dim_steps_alpha1/8x2_2/checkpoints
sample_dir: /home/czavou01/decorgan-models/mydp2patch2D_32dim_steps_alpha1/8x2_2/samples/
export_dir: /home/czavou01/decorgan-models/mydp2patch2D_32dim_steps_alpha1/8x2_2/encodings/
test_fig_3_dir: /home/czavou01/decorgan-models/mydp2patch2D_32dim_steps_alpha1/8x2_2/test_fig_3
style_codes_dir: /home/czavou01/decorgan-models/mydp2patch2D_32dim_steps_alpha1/8x2_2/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 1.
beta: 10.0

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
