
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

gen_dim: 32
disc_dim: 32
style_dim: 8

save_iter: 1000
log_iter: 500
model_module: runners.modelAEadj_flexdp2
recon_loss: MSE
lr: 0.0001
kernel: 5
dilation: True
pooling: max

data_filename: model_filled.binvox
style_filename: model_filled.binvox
datapath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/column_lun/export.txt
stylepath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/building_component/building_windowdoorcolumndometower_setAstyles32.txt
data_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2
style_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2
data_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/column_lun
style_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components

checkpoint_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_components/setA/adj_dp2/s32/checkpoints
sample_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_components/setA/adj_dp2/s32/samples
export_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_components/setA/adj_dp2/s32/encodings_column_lun
test_fig_3_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_components/setA/adj_dp2/s32/test_fig_3
style_codes_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/trained_on_buildnet_components/setA/adj_dp2/s32/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: False
export: True
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
