
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

save_iter: 1000
log_iter: 500
model_module: runners.style_encoder.modelAEadj_FS_batchdiv
recon_loss: MSE
lr: 0.0001
kernel: 5
dilation: True
pooling: max

data_filename: model_filled.binvox
style_filename: model_filled.binvox
val_filename: model_filled.binvox
datapath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/building_component/building_windowdoorcolumndometower_setBC.txt
stylepath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/building_component/building_windowdoorcolumndometower_setAstyles32.txt
valpath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/building_component/building_windowdoorcolumndometower_setAstyles32.txt
data_cache_dir:
style_cache_dir:
val_cache_dir:
data_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components
style_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components
val_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components

checkpoint_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_buildnet_component_setA/style_encoder/i16o128/g32d32z8/checkpoints
sample_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_buildnet_component_setA/style_encoder/i16o128/g32d32z8/samples
export_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_buildnet_component_setA/style_encoder/i16o128/g32d32z8/encodings_religious_and_annfass
test_fig_3_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_buildnet_component_setA/style_encoder/i16o128/g32d32z8/test_fig_3
style_codes_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_buildnet_component_setA/style_encoder/i16o128/g32d32z8/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: False
export: True
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
