
epoch: 25
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 128

batch_size: 4

save_iter: 2259
log_iter: 564
model_module: runners.any_style.modelAEany_share_xFreeSpeed_rot_mul_rndnoise_batchdiv
recon_loss: MSE
lr: 0.0001
margin: 0.2
kernel: 5
dilation: True
pooling: max

num_pairs: 64
num_triplets: 64

data_filename: model_filled.binvox
style_filename: model_filled.binvox
val_filename: model_filled.binvox
datapath: /mnt/beegfs/czavou01/decorgan-logs/splits/03001627_train_objs_norm_and_random_rot/chair_random_rot_train.txt
stylepath: /mnt/beegfs/czavou01/decorgan-logs/splits/03001627_train_objs_norm_and_random_rot/chair_random_rot_train.txt
valpath: /mnt/beegfs/czavou01/decorgan-logs/splits/03001627_test_objs_norm_and_random_rot/content_chair_random_rot_test.txt
data_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_i16o128_rndnoise_rot
style_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_i16o128_rndnoise_rot
val_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_i16o128_rndnoise_rot
style_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_train_objs_norm_and_random_rot
data_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_train_objs_norm_and_random_rot
val_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_test_objs_norm_and_random_rot

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/any_share_3/i16o128/g32d32z128/rndnoise_batch4_rot/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/any_share_3/i16o128/g32d32z128/rndnoise_batch4_rot/samples_again
export_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/any_share_3/i16o128/g32d32z128/rndnoise_batch4_rot/encodings
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/any_share_3/i16o128/g32d32z128/rndnoise_batch4_rot/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/any_share_3/i16o128/g32d32z128/rndnoise_batch4_rot/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 1.
beta: 10.0
gamma: 1.
delta: 1.

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
