
epoch: 40
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 128

num_pairs: 16
num_triplets: 32
margin: 0.2
patch_factor: 2
stride_factor: 1

batch_size: 4

save_iter: 654
log_iter: 654
model_module: runners.any_style.modelAEany_share_x_rot_same_batchdiv_same
lr: 0.0001
kernel: 5
dilation: True
pooling: max
clamp_num: 0.01
optim: Adam
with_norm: False
norm_type: group_norm
weight_init: False
weight_decay: 0
use_wc: False
group_norm: False

data_filename: model_filled.binvox
style_filename: model_filled.binvox
val_filename: model_filled.binvox
datapath: /home/czavou01/decorgan-logs/splits/chair/content_chair_train.txt
stylepath: /home/czavou01/decorgan-logs/splits/chair/content_chair_train.txt
valpath: /home/czavou01/decorgan-logs/splits/chair/content_chair_test.txt
data_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_rot_same/i16o128
style_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_rot_same/i16o128
val_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_rot_same/i16o128
style_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_train_objs_norm_and_specific_rot
data_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_train_objs_norm_and_specific_rot
val_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_test_objs_norm_and_specific_rot

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/i16o128/any_share_3/batch4/rot_same_same_triplets32pairs16/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/i16o128/any_share_3/batch4/rot_same_same_triplets32pairs16/samples
export_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/i16o128/any_share_3/batch4/rot_same_same_triplets32pairs16/encodings
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/i16o128/any_share_3/batch4/rot_same_same_triplets32pairs16/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/chair/any_style/i16o128/any_share_3/batch4/rot_same_same_triplets32pairs16/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 1.
beta: 10.0
gamma: 1.
delta: 1.

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
