
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 128

save_iter: 654
log_iter: 654
model_module: runners.style_encoder.modelAEadj_FS_batchdiv
batch_size: 4
with_norm: True
norm_type: group_norm
recon_loss: MSE
lr: 0.0001
kernel: 5
dilation: True
pooling: max
weight_init: False
weight_decay: 0
use_wc: False
group_norm: True


data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
val_filename: model_depth_fusion.binvox
datapath: /home/czavou01/decorgan-logs/splits/content_chair_train.txt
stylepath: /home/czavou01/decorgan-logs/splits/style_chair_64.txt
valpath: /home/czavou01/decorgan-logs/splits/chair/content_chair_test.txt
data_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
style_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
val_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
style_dir: /home/czavou01/decorgan-logs/data/03001627
data_dir: /home/czavou01/decorgan-logs/data/03001627
val_dir: /home/czavou01/decorgan-logs/data/03001627

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/chair/style_encoder/i16o128/g32d32z128/batch4/groupnorm/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/chair/style_encoder/i16o128/g32d32z128/batch4/groupnorm/samples
export_dir: /mnt/beegfs/czavou01/decorgan-models/chair/style_encoder/i16o128/g32d32z128/batch4/groupnorm/encodings
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/chair/style_encoder/i16o128/g32d32z128/batch4/groupnorm/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/chair/style_encoder/i16o128/g32d32z128/batch4/groupnorm/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
