logs: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/2dae_results/train_on_buildnet/bn
data_dir: /mnt/beegfs/czavou01/ANNFASS_DATA/BUILDNET_Buildings/groups_june17_renderings/materials_on_daylight
train_txt: /mnt/beegfs/czavou01/2dae_train.txt
val_txt: /mnt/beegfs/czavou01/2dae_val.txt
test_csv: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/style_detection/logs_final/labeled_data/2dae_export.csv
encodings_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/2dae_results/train_on_buildnet/bn/encodings
mode: encode
batch_size: 16
num_workers: 0
z_dim: 16
num_channels: 4
batch_norm: True
epochs: 300

