
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

patch_num: 1
patch_factor: 1
stride_factor: 1

save_iter: 1000
log_iter: 500
model_module: runners_pytorch3d.modelAEadj_dp2
cycle_factor: 10
recon_loss: MSE
cycle_loss: L1
lr: 0.0001
se_lr: 0.0001
style_dim: 32
nt_xent_factor: 1.
tau: 0.5
style_batch: 4
kernel: 5
dilation: True
pooling: max

buildings_dir:
filename: model_filled.binvox
datapath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/fig3_content_groups_june17_uni_nor_components_tower_steepledomedoorwindowcolumn.txt
cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2
stylepath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/groups_june17_uni_nor_components_tower_steepledomedoorwindowcolumn_styles64.txt
#style_indices: "6, 17, 21, 22, 25, 27, 3, 15, 20"
#style_indices: "6, 1, 9, 3, 4, 12, 15"
#style_indices: "2, 3, 7, 8, 11, 14, 15, 16"
style_indices: "0, 3, 4, 8, 11, 15, 17, 24, 26, 27, 29, 31"

data_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/preprocessed_data/groups_june17_uni_nor_components
checkpoint_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/aug02/groups_june17_uni_nor_components/adj_dp2/s32/checkpoints
sample_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/aug02/groups_june17_uni_nor_components/adj_dp2/s32/samples_again
export_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/aug02/groups_june17_uni_nor_components/adj_dp2/s32/encodings
test_fig_3_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/aug02/groups_june17_uni_nor_components/adj_dp2/s32/test_fig_3
style_codes_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/aug02/groups_june17_uni_nor_components/adj_dp2/s32/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: True
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
