
epoch: 50
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

gen_dim: 32
disc_dim: 32
style_dim: 32

save_iter: 3141
log_iter: 785
model_module: runners.modelAE_flexdp2
recon_loss: MSE
lr: 0.0001
margin: 0.2
kernel: 5
dilation: True
pooling: max

data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
datapath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/car/fig_3_car_content.txt
stylepath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/car/style_car_32.txt
data_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2_in16_out128
style_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2_in16_out128
style_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/02958343
data_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/02958343
style_indices: "10, 11, 13, 17, 27, 29"

checkpoint_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep19/trained_on_shapenet_cars/original_clean/s16_i32o256/checkpoints
sample_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep19/trained_on_shapenet_cars/original_clean/s16_i32o256/samples_again
export_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep17/sep19/trained_on_shapenet_cars/original_clean/s16_i32o256/encodings
test_fig_3_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep19/trained_on_shapenet_cars/original_clean/s16_i32o256/test_fig_3
style_codes_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/sep19/trained_on_shapenet_cars/original_clean/s16_i32o256/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: True
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
