
epoch: 25
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 128

num_pairs: 64
num_triplets: 128
margin: 0.2
patch_factor: 2
stride_factor: 1

batch_size: 1

save_iter: 1882
log_iter: 1882
model_module: runners.any_style.modelAEany_share_x_rot_same_batchdiv
lr: 0.0001
kernel: 5
dilation: True
pooling: max
clamp_num: 0.01
optim: Adam
with_norm: False
norm_type: group_norm
weight_init: False
weight_decay: 0
use_wc: False
group_norm: False

data_filename: model_filled.binvox
style_filename: model_filled.binvox
val_filename: model_filled.binvox
datapath: /home/czavou01/decorgan-logs/splits/car/content_car_train_2Knoyu.txt
stylepath: /home/czavou01/decorgan-logs/splits/car/content_car_train_2Knoyu.txt
valpath: /home/czavou01/decorgan-logs/splits/car/content_car_test_470.txt
data_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_rot_same/i64o1256
style_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_rot_same/i64o1256
val_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_rot_same/i64o1256
style_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/02958343_train_objs_norm_and_specific_rot
data_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/02958343_train_objs_norm_and_specific_rot
val_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/02958343_test_objs_norm_and_specific_rot

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/car_noyu/any_style/i64o256/any_share_3/batch1/rot_same/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/car_noyu/any_style/i64o256/any_share_3/batch1/rot_same/samples
export_dir: /mnt/beegfs/czavou01/decorgan-models/car_noyu/any_style/i64o256/any_share_3/batch1/rot_same/encodings
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/car_noyu/any_style/i64o256/any_share_3/batch1/rot_same/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/car_noyu/any_style/i64o256/any_share_3/batch1/rot_same/style_codes

input_size: 64
output_size: 256

asymmetry: True

alpha: 1.
beta: 10.0
gamma: 1.
delta: 1.

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
