
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

gen_dim: 32
disc_dim: 32
style_dim: 8

patch_num: 1
patch_factor: 1
stride_factor: 1

save_iter: 70
log_iter: 35
model_module: runners.style_encoder.modelAEadj_rot_mul_batchdiv
lr: 0.0001
se_lr: 0.0001
style_batch: 4
kernel: 5
dilation: True
pooling: max

data_filename: model_filled.binvox
style_filename: model_filled.binvox
datapath: /mnt/beegfs/czavou01/decorgan-logs/splits/03001627_train_objs_norm_and_random_rot/chair_random_rot_train.txt
stylepath: /mnt/beegfs/czavou01/decorgan-logs/splits/03001627_train_objs_norm_and_random_rot/style_chair_random_rot_64.txt
data_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
style_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
style_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_train_objs_norm_and_random_rot
data_dir: /mnt/beegfs/czavou01/decorgan-logs/preprocessed_data/03001627_train_objs_norm_and_random_rot

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/style_encoder/i16o128/g32d32z8/b32_rot/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/style_encoder/i16o128/g32d32z8/b32_rot/samples/
export_dir: /mnt/beegfs/czavou01/decorgan-models/style_encoder/i16o128/g32d32z8/b32_rot/encodings/
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/style_encoder/i16o128/g32d32z8/b32_rot/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/style_encoder/i16o128/g32d32z8/b32_rot/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
