
epoch: 50
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 128

save_iter: 1000
log_iter: 500
model_module: runners.any_style.modelAEany_share_3FreeSpeed
recon_loss: MSE
lr: 0.0001
margin: 0.2
kernel: 5
dilation: True
pooling: max

data_filename: model_filled.binvox
style_filename: model_depth_fusion.binvox
datapath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/HU_YU_LUN_BUILDNET/splits/furniture_hu_norm_and_align/export.txt
stylepath: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/splits/chair/style_chair_64.txt
data_cache_dir:
style_cache_dir:
data_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/HU_YU_LUN_BUILDNET/preprocessed_data/furniture_hu_norm_and_align
style_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan-logs/data/03001627

checkpoint_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/any_share_3Free_m02_s128.good/checkpoints
sample_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/any_share_3Free_m02_s128.good/samples_again
export_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/any_share_3Free_m02_s128.good/encodings_furniture_hu_norm_and_align
test_fig_3_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/any_share_3Free_m02_s128.good/test_fig_3
style_codes_dir: /media/graphicslab/BigData1/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share_3/any_share_3Free_m02_s128.good/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 1.
beta: 10.0
gamma: 1.
delta: 1.

train: False
style_codes: False
test_fig_3: False
export: True
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
