
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4
batch_size: 1

patch_num: 1
patch_factor: 1
stride_factor: 1

gen_dim: 32
disc_dim: 32

save_iter: 2000
log_iter: 500
model_module: runners.adain.modelAEadain_layers
lr: 0.0001
se_lr: 0.0001
style_batch: 4
kernel: 5
dilation: True
pooling: max

data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
datapath: /home/czavou01/decorgan-logs/splits/content_chair_train.txt
stylepath: /home/czavou01/decorgan-logs/splits/style_chair_64.txt
data_cache_dir: /home/czavou01/decorgan-logs/data_cached_2_in16_out128
style_cache_dir: /home/czavou01/decorgan-logs/data_cached_2_in16_out128
data_dir: /home/czavou01/decorgan-logs/data/03001627
style_dir: /home/czavou01/decorgan-logs/data/03001627

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/samples
export_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/encodings
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: False
export: False
debug: False

output_for_eval_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/output_for_eval
output_for_FID_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/output_for_FID
eval_output_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/layers/eval_output

cls_dir: /home/czavou01/decorgan-logs/Clsshapenet_weights
unique_patches_dir: /home/czavou01/decorgan-models/unique_patches_64_chairs_i16o128

prepvox: True
prepvoxstyle: True
evalvox: True

prepimg: False
prepimgreal: False
evalimg: False

prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
