
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 32

save_iter: 2000
log_iter: 500
model_module: runners.modelAEadj_flexdp2_share_Speed
recon_loss: MSE
lr: 0.0001
kernel: 5
dilation: True
pooling: max

data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
datapath: /home/czavou01/decorgan-logs/splits/content_chair_train.txt
stylepath:  /home/czavou01/decorgan-logs/splits/style_chair_64.txt
data_cache_dir: /home/czavou01/decorgan-logs/data_cached_2_in32_out256
style_cache_dir: /home/czavou01/decorgan-logs/data_cached_2_in32_out256
style_dir: /home/czavou01/decorgan-logs/data/03001627
data_dir: /home/czavou01/decorgan-logs/data/03001627

checkpoint_dir: /home/czavou01/decorgan-models/chair/style_encoder/share_in32_out256_z32_speed/checkpoints
sample_dir: /home/czavou01/decorgan-models/chair/style_encoder/share_in32_out256_z32_speed/samples/
export_dir: /home/czavou01/decorgan-models/chair/style_encoder/share_in32_out256_z32_speed/encodings/
test_fig_3_dir: /home/czavou01/decorgan-models/chair/style_encoder/share_in32_out256_z32_speed/test_fig_3
style_codes_dir: /home/czavou01/decorgan-models/chair/style_encoder/share_in32_out256_z32_speed/style_codes

input_size: 32
output_size: 256

asymmetry: True

alpha: 0.5
beta: 10.0

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
