
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

batch_size: 32

patch_num: 1
patch_factor: 1
stride_factor: 1

gen_dim: 32
disc_dim: 32

save_iter: 2000
log_iter: 500
model_module: runners.modelAEadain_FS_batch2div
lr: 0.0001
style_batch: 4
kernel: 5
dilation: True
pooling: max

data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
datapath: /home/czavou01/decorgan-logs/splits/content_chair_train.txt
stylepath: /home/czavou01/decorgan-logs/splits/style_chair_64.txt
data_cache_dir: /home/czavou01/decorgan-logs/data_cached_2_in16_out128
style_cache_dir: /home/czavou01/decorgan-logs/data_cached_2_in16_out128
data_dir: /home/czavou01/decorgan-logs/data/03001627
style_dir: /home/czavou01/decorgan-logs/data/03001627

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/b2_b32div/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/b2_b32div/samples
export_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/b2_b32div/encodings
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/b2_b32div/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/chair/adain/i16o128/g32d32/b2_b32div/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
