
epoch: 100
iteration: 0

g_steps: 5
d_steps: 1
r_steps: 4

gen_dim: 32
disc_dim: 32
style_dim: 8

save_iter: 564
log_iter: 564
batch_size: 4
model_module: runners.original.modelAE_batchdiv_w_gan
recon_loss: MSE
lr: 0.00005
se_lr: 0.00005
kernel: 5
dilation: True
pooling: max

data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
val_filename: model_depth_fusion.binvox
datapath: /home/czavou01/decorgan-logs/splits/content_chair_train.txt
stylepath: /home/czavou01/decorgan-logs/splits/style_chair_64.txt
valpath: /home/czavou01/decorgan-logs/splits/chair/content_chair_test.txt
data_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
style_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
val_cache_dir: /mnt/beegfs/czavou01/decorgan-logs/data_cached_2_i16o128
style_dir: /home/czavou01/decorgan-logs/data/03001627
data_dir: /home/czavou01/decorgan-logs/data/03001627
val_dir: /home/czavou01/decorgan-logs/data/03001627

checkpoint_dir: /mnt/beegfs/czavou01/decorgan-models/chair/original/i16o128/g32d32z8/batch4/w_gan_g/checkpoints
sample_dir: /mnt/beegfs/czavou01/decorgan-models/chair/original/i16o128/g32d32z8/batch4/w_gan_g/samples/
export_dir: /mnt/beegfs/czavou01/decorgan-models/chair/original/i16o128/g32d32z8/batch4/w_gan_g/encodings/
test_fig_3_dir: /mnt/beegfs/czavou01/decorgan-models/chair/original/i16o128/g32d32z8/batch4/w_gan_g/test_fig_3
style_codes_dir: /mnt/beegfs/czavou01/decorgan-models/chair/original/i16o128/g32d32z8/batch4/w_gan_g/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 0.5
beta: 10.0

train: True
style_codes: False
test_fig_3: False
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
