
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

disc_dim: 32
gen_dim: 32
style_dim: 32

save_iter: 1000
log_iter: 500
model_module: runners.style_encoder.modelAEadj_flexdp2_share_Speed
recon_loss: MSE
lr: 0.0001
se_lr: 0.0001
kernel: 5
dilation: True
pooling: max

data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
datapath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/chair/chair_fig3_content.txt
stylepath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/chair/style_chair_64.txt
data_cache_dir:
style_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2_in32_out256
data_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/03001627
style_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/03001627
style_indices: "6, 17, 21, 22, 25, 27, 3, 15, 20"

checkpoint_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/style_encoder/i32o256/share_z32_speed/checkpoints
sample_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/style_encoder/i32o256/share_z32_speed/samples
export_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/style_encoder/i32o256/share_z32_speed/encodings
test_fig_3_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/style_encoder/i32o256/share_z32_speed/test_fig_3
style_codes_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/style_encoder/i32o256/share_z32_speed/style_codes

input_size: 32
output_size: 256

asymmetry: True

alpha: 0.5
beta: 10.0

train: False
style_codes: False
test_fig_3: True
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
