
SOLVER:
  gpu: 0,
  max_iter: 144000 #60 epochs
  test_iter: 200 
  test_every_iter: 2400
  run: train
  gamma: 0.1
  learning_rate: 0.1
  lr_type: 'cos'
  #step_size: (30000,)

DATA:
  train:
    dtype: points
    depth: 8
    axis: y
    node_dis: False
    shuffle: True
    take: -1
    adaptive: False
    location: "/mnt/nfs/work1/kalo/maverkiou/maria/withcolor"
    file_list: "/mnt/nfs/work1/kalo/maverkiou/maria/splits/train_split.txt"
    label_location: "/mnt/nfs/work1/kalo/maverkiou/maria/point_labels_32"
    batch_size: 8
    mask_ratio: 0.7
    rot_num: 12
    return_pts: True
    use_majority: False
    hsv: False

  test: 
    dtype: points
    depth: 8
    axis: y
    node_dis: False
    adaptive: False
    location: "/mnt/nfs/work1/kalo/maverkiou/maria/withcolor"
    file_list: "/mnt/nfs/work1/kalo/maverkiou/maria/splits/val_split.txt"
    label_location: "/mnt/nfs/work1/kalo/maverkiou/maria/point_labels_32"
    shuffle: True
    batch_size: 1
    sigma: 0.0
    rot_num: 1
    mask_ratio: 0.0
    return_pts: True
    use_majority: False
    hsv: False


MODEL:
  name: hrnet
  channel: 3
  nout: 31
  depth: 8
  factor: 2
  signal_abs: True
  stages: 3

LOSS:
  num_class: 31
  momentum: 0.9
  weight_decay: 0.0005
  point_wise: True
  class_weights: ./configs/loss_weights/class_weights.txt
