
epoch: 20
iteration: 0

g_steps: 1
d_steps: 1
r_steps: 4

gen_dim: 32
disc_dim: 32
style_dim: 128

stride_factor: 2
num_triplets: 256
num_pairs: 256

batch_size: 32

save_iter: 70
log_iter: 35
model_module: runners.any_style.modelAEany_share_3_batchdiv
recon_loss: MSE
lr: 0.0001
se_lr: 0.0001
kernel: 5
dilation: True
pooling: max

data_filename: model_depth_fusion.binvox
style_filename: model_depth_fusion.binvox
datapath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/chair/chair_fig3_content.txt
stylepath: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/splits/chair/style_chair_64.txt
data_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2_in16_out128
style_cache_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data_cached_2_in16_out128
data_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/03001627
style_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan-logs/data/03001627
style_indices: "6, 17, 21, 22, 25, 27, 3, 15, 20"

checkpoint_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share3_batch32/checkpoints
sample_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share3_batch32/samples_again
export_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share3_batch32/encodings
test_fig_3_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share3_batch32/test_fig_3
style_codes_dir: /media/graphicslab/BigData/zavou/ANNFASS_CODE/decorgan_results/from_turing/trained_on_chairs/any_style/i16o128/any_share3_batch32/style_codes

input_size: 16
output_size: 128

asymmetry: True

alpha: 1.
beta: 10.0
gamma: 1.
delta: 1.

train: False
style_codes: False
test_fig_3: True
export: False
debug: False

prepvox: False
prepvoxstyle: False
evalvox: False
prepimg: False
prepimgreal: False
evalimg: False
prepFID: False
prepFIDmodel: False
prepFIDreal: False
evalFID: False
ui: False
