
build:
	mkdir -p rtsc-1.6/build \
		&& rm -rf rtsc-1.6/build/* \
		&& cd rtsc-1.6/build \
		&& cmake .. \
		&& make

build-on-gypsum:
	mkdir -p rtsc-1.6/build \
		&& rm -rf rtsc-1.6/build/* \
		&& cd rtsc-1.6/build \
		&& cmake3 .. \
		&& make
